import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/widgets/sidebar";
import { MobileHeader } from "@/widgets/header";

const groteskSans = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <body className={`${groteskSans.variable} font-sans antialiased overflow-hidden`}>
    <div className="flex flex-col lg:flex-row">
      <MobileHeader />
      <div className="hidden lg:flex">
        <Sidebar />
      </div>
      <main className="w-full lg:h-screen overflow-y-auto">
        {children}
      </main>
    </div>
    </body>

    </html>
  );
}
